.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. nautiluscoin_qt test_nautiluscoin_qt
clean: FORCE
	$(MAKE) -C .. nautiluscoin_qt_clean test_nautiluscoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_nautiluscoin_qt_check
nautiluscoin-qt nautiluscoin-qt.exe: FORCE
	 $(MAKE) -C .. nautiluscoin_qt
