#!/bin/bash

# This is a thin wrapper around nautiluscoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using nautiluscoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_NAUTILUSCOIND

# Grab the value of $REAL_NAUTILUSCOINCLI which may be nautiluscoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_NAUTILUSCOINCLI}" "$@" | sed 's/\r//'
